wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739863874
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.11.11
      5: 0.19.6
      8:
      - 5
      13: linux-x86_64
mid_channels:
  desc: null
  value: 32
kernel_size:
  desc: null
  value: 7
mid_layers:
  desc: null
  value: 1
hidden_dim:
  desc: null
  value: 128
reg_weight:
  desc: null
  value: 0.005
temp:
  desc: null
  value: 1
