_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
hidden_dim:
    value: 256
kernel_size:
    value: 3
mid_channels:
    value: 64
mid_layers:
    value: 3
reg_weight:
    value: 0.0002
temp:
    value: 1
